#!/usr/bin/env python
"""
Detect Carp Species from an eDNA sequence.

This script uses Biopython’s pairwise2 module to locally align an input 
query sequence to one of four carp species reference sequences:
- Bighead Carp
- Silver Carp
- Grass Carp
- Black Carp

It then selects the species with the highest percent identity (if above a threshold).

Before running, install Biopython with:
    pip install biopython
"""

from Bio import pairwise2
from Bio.Seq import Seq

# Define reference sequences for each carp species (example sequences).
# These sequences are derived from available eDNA records.
# In practice, adjust these sequences to match your full reference data.

ref_sequences = {
    "Bighead Carp": (
        "CTTCTGGTAGTACCTATATGGTTCAGTACATATTATGTATTATGTTACCTAATGTACTAATACCTATATATG"
        "TATTATCACCATTAATTTATTTTAACCTTAAAGCAAGTACTAACGTTTAAAAACGTACATAAACCAAAAT"
        "ATTAAGATTCATAAATAAATTATCTTAACTTAAATAAACAGATTATTCCACTAACAATTGATTCTCAAATT"
        "TATTACTGAATTATTAACTAAAATCTAACTCAAGTATATTATTAAAGTAAGAGACCACCTACTTATTTATA"
        "TTAAGGTATTATATTCATGATAAGATCAAGGACAATAACAGTGGGGGTGGCGCAAAATGAACTATTAC"
        "TTGCATCTGGTTTGGAATCTCACGGACATGGCTACAAAATTCCACCCCCGTTACATTATAACTGGCATA"
        "TGGTTAAATGATGTGAGTACATACTCCTCATTAACCCCACATGCCGAGCATTCTTTTATATGCATAGGG"
        "GTTCTCCTTTTGGTTTCCTTTCACCTTGCATATCAGAGTGCAAGCTCAAATAGTAAAATAAGGTTGAAC"
        "ATATTCCTTGCTTGTGTTAAAGTAAGTTAATTATTAAAAGACATAACTTAAGAATTACATATTTCTCACTC"
        "AAGTGCATAACATATTCATTCTTTCTTCAACTTACCCCTATATATATGCCCCCCCTTTTGGCTTCTGCGC"
        "GACAAACCCCCCTACCCCCTACGCTCAGCAAATCCTGTTATCCTTGTCAAACCCCAAAACCAAGGAA"
        "GGTTCGAGAACGTGCAAGCTAACAAGTTGAAATATGGGTTAGCTATCCGCATTATATATATATATATAC"
        "ATACACATCACATCAATTTACCACATAATTCCCCAAACATTGACCTAAAAACCCCTATTAAATTTATAGG"
        "ACATGCCCCAATGCTAAAAAGTCCAACATTATATAATGCTAG"
    ),
    "Silver Carp": (
        "TCTTCTGATATAACCTATATGGTTTAATACATATATGTATTATATTACATAATGCATTAGTACTAGTATATG"
        "TATTATCACCATTCATTTATATTAACCTTAAAGCAAGTACTAACGTTTAAGACGTACATAAACCAAATAT"
        "TTAAAATTCACAATTAATTTATTTAAACCTGAGAAAAGAGTTGTTCCACTATAATTGGTTCTCAAATATTT"
        "CCTTGAAATATTAACTTCTATTTAATTTAACTATATTAATGTAGTAAGAAACCACCTACTGGTTTATATTA"
        "AGGTATTCTATTCATGATAAGATCAGGGACAATAATCGTGGGGGTGGCGCAGAATGAACTATTACTTG"
        "CATTTGGCTTGGAATCTCACGGACATGACTGTAAAATTCCACCCTCCATACATTATATCTGGCATCTGG"
        "TTAAATGATGTGAGTACATACTCCTCATTAACCCCACATGCCGAGCATTCTTTTATATGCATAGGGGTTC"
        "TCCTTTTGGTTACCTTTCATCTTGCATATCAGAGTGCAGGCTCAAATGATAAATTAAGGTTGAACATATT"
        "CCTTGCTTAAGTTAAAGTAGGTTAATTATTGAAAGACATAACTTAAGAATTACATATTTTTAATTCAAGT"
        "GCATAACATATTATTCTTTCTTCAACTTACCCTTATATATATGCCCCCCTTTCGGTTTCTGCGCGACAAA"
        "CCCCCTTACCCCCTACGCTCAACAAATCCTGTTATCCTTGTCAAACCCCAAAACCAAGGAAGGTTCGA"
        "GAACGTGCAAGCTAACAAGTTGAAATATGAGTTAGCTATCCGCATTATATATATATATATACATACACAT"
        "CGCGTCAATTCGCCACATAATTCCCCAAATATAAACCTAAAAATTCCTATTAAATTTTAAGGGGCACGC"
        "CCCAATGCTAAAAAGTCCAACATTAAATAACGCTAGCGTAG"
    ),
    "Grass Carp": (
        "GACATTGCTACCCTCTATCTTGTATTTGGTGCCTGAGCCGGAATAGTGGGAACCGCTCTAAGCCTTCTC"
        "ATTCGAGCCGAACTAAGCCAACCCGGATCACTTCTGGGCGATGATCAAATTTATAATGTTATTGTCACT"
        "GCCCATGCCTTCGTAATAATTTTCTTTATAGTAATACCAATTCTTATTGGAGGGTTTGGAAATTGACTCG"
        "TACCATTAATAATTGGAGCACCCGACATAGCATTCCCACGAATAAACAACATGAGTTTCTGACTTCTAC"
        "CCCCTTCTTTCCTCCTACTATTAGCCTCTTCTGGTGTTGAGGCCGGAGCTGGAACAGGGTGAACAGTT"
        "TACCCACCACTCGCAGGCAATCTTGCCCACGCAGGAGCATCCGTAGACCTAACAATTTTCTCACTCCA"
        "CCTGGCAGGTGTGTCATCAATTTTAGGGGCAATTAATTTTATTACTACAACCATTAACATGAAACCACC"
        "AGCCATCTCCCAATACCAAACACCTCTCTTCGTTTGAGCTGTACTTGTAACAGCTGTACTCCTTCTTCTA"
        "TCTCTACCAGTTCTAGCCGCCGGAATTACAATACTCCTAACAGACCGTAATCTTAACACTACATTCTTT"
        "GACCCGGCGGGAGGAGGAGACCCAATTCTTTATCAACACTTATTCTGATTCTTTGGTCACCCGGAAGT"
        "TTATATTCTTATTTTACCCGGATTTGGAATCATTTCACATGTTGTAGCCTACTATGCAGGTAAAAAAGAA"
        "CCATTCGGTTATATAGGAATAGTCTGAGCTATAATGGCTATTGGTCTTCTAGGGTTTATTGTATGAGCCC"
        "ACCATATGTTTACTGTTGGGATAGACGTAGACACTCGTGCATATTTTACATCCGCAACGATAATTATTG"
        "CTATCCCAACAGGTGTAAAAGTATTTAGCTGACTAGCCACAC"
    ),
    "Black Carp": (
        "GACATTGGTACCCTTTATCTTGTATTTGGTGCCTGAGCCGGAATAGTGGGAACCGCTCTAAGCCTTCTC"
        "ATTCGAGCCGAACTAAGCCAACCCGGATCACTTCTGGGCGATGACCAAATTTATAATGTTATTGTCAC"
        "TGCCCATGCCTTCGTAATAATTTTCTTTATAGTAATACCAATTCTTATTGGAGGATTCGGAAACTGACTC"
        "GTACCGCTAATAATTGGAGCACCTGATATAGCATTCCCCCGAATGAATAACATAAGCTTCTGACTTCTG"
        "CCCCCATCTTTCCTCCTACTACTAGCCTCTTCTGGTGTTGAAGCTGGGGCTGGGACAGGGTGAACAGT"
        "CTACCCACCACTCGCAGGCAATCTTGCACACGCAGGAGCATCTGTAGATCTAACAATCTTTTCGCTAC"
        "ACCTGGCAGGTGTGTCATCAATTTTAGGAGCGATTAACTTCATCACTACAACTATCAACATAAAACCCC"
        "CAGCCATTTCTCAATACCAAACACCTCTCTTTGTCTGAGCTGTGCTAGTAACAGCCGTACTCCTTCTCC"
        "TATCCCTACCAGTCCTAGCTGCTGGAATTACAATACTCCTTACAGACCGTAACCTTAACACCACGTTCT"
        "TTGACCCAGCAGGCGGAGGAGACCCAATCCTATATCAACACCTGTTCTGATTCTTCGGCCACCCAGA"
        "AGTTTACATTCTTATTTTACCCGGGTTTGGGATCATTTCACACGTCGTAGCCTACTACGCGGGCAAAAA"
        "AGAACCATTTGGTTACATAGGAATGGTTTGAGCCATGATGGCTATTGGTCTCCTAGGATTTATTGTGTG"
        "AGCCCACCACATGTTTACTGTCGGAATAGACGTAGACACTCGTGCATACTTTACATCCGCAACAATAA"
        "TTATTGCTATCCCAACAGGTGTAAAAGTGTTTAGCTGACTAGCC"
    )
}


def detect_carp_species(query_seq, ref_dict, threshold=0.90):
    """
    Compare a query sequence to reference sequences for each carp species.
    Returns the species with the highest percent score above the threshold
    or None if no species passes the threshold.

    Args:
        query_seq (str): The eDNA sequence to identify.
        ref_dict (dict): A dictionary of {species_name: reference_sequence}.
        threshold (float): The minimum fraction of the maximum possible score required.
                           (Default: 0.90)

    Returns:
        (species, percent_score) or (None, percent_score) if no good match.
    """
    best_species = None
    best_percent = 0.0

    for species, ref in ref_dict.items():
        # Use local alignment (Smith-Waterman) for flexibility in matching.
        alignments = pairwise2.align.localms(query_seq, ref, 2, -1, -0.5, -0.1)
        if not alignments:
            continue
        best_alignment = alignments[0]  # best alignment
        score = best_alignment[2]
        # Calculate the maximum possible score if the entire ref is matched perfectly.
        max_possible = len(ref) * 2  # since match score is +2
        percent_similarity = score / max_possible

        print(f"Species: {species} | Alignment Score: {score:.2f} | Percent Similarity: {percent_similarity:.2%}")

        if percent_similarity > best_percent:
            best_percent = percent_similarity
            best_species = species

    if best_species and best_percent >= threshold:
        return best_species, best_percent
    else:
        return None, best_percent


if __name__ == "__main__":
    # In a typical Windows environment, you might load the query sequence from a file
    # or another source. For demonstration, we define one here directly.
    # Replace or modify this as needed.
    query_eDNA = (
        """
        GACATTTGGAGATTAAATATTGTGTGGGCGTGCACTGCGCTGACGAATACTTCGATGTTGGTGTTGAG
        TTTGATTACGTTGACTGCTGCCAAGGATAAGATGTTGGATACATTCGAATTGGAATATTATCGGTGGGC
        ATTTACTACCTCCACCACATTTAAGTTGAGAGTAATATTGCGGTGCAGGTGGTCCTTATTTACAACGGG
        ATAGGTGGAGAAGACATCGACATATGTCGCTAGATGGGATAGTTCTAATAAGAAGGAGGCTGAGTTT
        AATACCGCGAAAACGCGGGACTGCATGACTTATATGTTATCCACCCGTGAGTAAAGCACAAATATTTA
        GATGAGCACTTGCCGATTTGGGAGTGGCGAGGGCCGCTTGCACTTCCAAGACGCCCAATTCTGTGAA
        CTTGGTGTAGGTCACTTCAATGAACTTAATTTCCAGTATGGTGCCCTCAGCATTAAAGGGAGAAGCGG
        AAAAAACAATTAGGGCCGGATAGAGGCGTATGCTTTAGCTTGGTCGAAGAAGGGGTGGGAGACGAA
        GATTAAGGTGGAGGCCACCAGGTCCAAATGCATGTCGATTCTGAAGAAGGCCACTGGGATTTCCCGG
        GCCCAGTAGGGTATATCGTCGACTTGATGATCTCCCTACCAAGCCGGGCACTTAGCAGCCTGAGGCC
        GTGTTGACCAGGGAGGCGCGCACTTTATTATAGCGGGATGCGTCCATTGCAGAGACTAGGTTTTTCAA
        GCAAGAATAGAACTGGTGCATGGTGCTTGCTACCCTCTATCTTGTATTTTTAGTGGGTTGTTGATGATG
        ACTTGTGGTGCCGCGGCAACTGCCCCTGCCCATACCCGCAATACGTGATTTATTATTGACCAGGTAGT
        GGTTGGGGGATACGACCTCCAGGCATACCAAGGCGTTGC"""
    )

    species, similarity = detect_carp_species(query_eDNA, ref_sequences, threshold=0.85)
    if species:
        print(f"\nDetected species: {species} (Similarity: {similarity:.2%})")
    else:
        print(f"\nNo species detected with a similarity above the threshold. Best similarity was {similarity:.2%}.")
